export const projects = [
  {
    slug: "scamcheck",
    title: "ScamCheck",
    result: "Scam messages → a clear risk verdict in seconds",
    problem: "Fake investments, OTP phishing, and fake bank alerts reach people every day, and most have no quick way to check what is real.",
    solution: "We built ScamCheck, a free tool that scores any link, message, or phone number, highlights the risky phrases, explains the verdict, and learns from user reports.",
    outcome: "Live tool with domain-age checks, verified community reports, and a Spot the Scam quiz.",
  },
  {
    slug: "secuscan",
    title: "SecuScan",
    result: "Hidden attack surfaces → 30s automated audit",
    problem: "Most business systems launch with hidden vulnerabilities across auth, headers, and exposed endpoints.",
    solution: "We built an automated audit engine with OWASP compliance, Docker-isolated scanning, and instant fix instructions.",
    outcome: "Over 500+ security audits performed with sub-30s turnaround.",
  },
  {
    slug: "luxehair",
    title: "Luxe Hair Co",
    result: "Manual DM ordering → sub-second WhatsApp checkout",
    problem: "High-end retail brands lose buyers to sluggish manual DM negotiations and fragmented order tracking.",
    solution: "We designed and launched a lightweight React storefront with live Naira catalogues and 1-tap cart-to-WhatsApp dispatch.",
    outcome: "40% increase in checkout conversions within the first 30 days.",
  },
  {
    slug: "carbreezy",
    title: "CarBreezy",
    result: "Opaque dealership listings → verified inspection reports",
    problem: "Vehicle buyers face opaque dealer pricing, fragmented condition reporting, and slow response times.",
    solution: "We built a high-performance inventory platform with instant spec lookups, 360 photo inspection, and direct dealer inquiry.",
    outcome: "150+ verified vehicle listings and sub-100ms faceted search.",
    image: "/work/carbreezy.webp",
    gallery: [
      "/work/work-carbreezy-inventory.webp",
      "/work/work-carbreezy-ferrari.webp",
    ],
  },
  {
    slug: "junicash",
    note: "Demo project. JuniCash is a portfolio build, not a licensed bank. Never enter real card or bank details.",
    title: "JuniCash",
    result: "Branch queues → banking from your phone",
    problem: "Everyday banking still means queues, paperwork, and apps built for banks instead of people.",
    solution: "We built JuniCash, a mobile-first digital banking app with simple onboarding, clear balances, and an easy-to-read transaction history.",
    outcome: "A working digital bank experience that can be understood in seconds.",
  },
];
